# Generated by Django 4.2.16 on 2024-09-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TempByLocationApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
